@startuml
Title Write 32bytes ADPCM data to external memory

scale 100 as 100 pixels
hide time-axis

concise "OPNA register write" as OPNA
concise "OPNA register R08 write" as OUT
binary "status:EOS" as EOS
binary "MDEN" as MDEN
concise "write data to memory" as WR

@0 as :start
@800 as :lasthalf
@1400 as :stopseq

'----------------------------------------------------------------

@:start
OPNA is "ADDRESS"
note top of OPNA: START 
OUT is {-}
WR is {-}

@:start+100
OPNA is {-}
OUT is "D0D1"
OUT -> MDEN@+30
@+30
MDEN is high
WR is "D0D1"
@+10
MDEN is low
@+70
WR is {-}

@:start+200
OUT is "D2D3"
OUT -> MDEN@+30
@+30
MDEN is high
WR is "D2D3"
@+10
MDEN is low
@+70
WR is {-}

@:start+300
OUT is "D4D5"
OUT -> MDEN@+30
@+30
MDEN is high
WR is "D4D5"
@+10
MDEN is low
@+70
WR is {-}

@:start+400
OUT is "D6D7"
OUT -> MDEN@+30
@+30
MDEN is high
WR is "D6D7"
@+10
MDEN is low
@+70
WR is {-}

@:start+500
OUT is "D8D9"
@+30
MDEN is high
WR is "D8D9"
@+10
MDEN is low
@+70
WR is {-}

@:start+600
OUT is "D10D11"
@+30
MDEN is high
WR is "D10D11"
@+10
MDEN is low
@+70
WR is {-}

@:start+700
note top of OPNA: snip
OPNA is {hidden}
OUT is {hidden}
MDEN is {hidden}
WR is {hidden}

'----------------------------------------------------------------

highlight 700 to 800 #Gray

'----------------------------------------------------------------

@:lasthalf
OPNA is {-}
OUT is "D62D63"
WR is {-}
OUT -> MDEN@+30
@+30
MDEN is high
WR is "D62D63"
@+10
MDEN is low
@+70
WR is {-}

@:lasthalf+100
EOS is high

@:lasthalf+100
OPNA is {-}
OUT is "X0X1"
WR is {-}
OUT -> MDEN@+30
@+30
MDEN is high
note top of WR: return to START ADDRESS 
WR is "X0X1"
@+10
MDEN is low
@+70
WR is {-}

@:lasthalf+200
OPNA is {-}
OUT is "X2X3"
WR is {-}
OUT -> MDEN@+30
@+30
MDEN is high
WR is "X2X3"
@+10
MDEN is low
@+70
WR is {-}

@:lasthalf+300
OUT is {-}
EOS is high



@enduml